name: "Deploy Beta"

on:
  release:
    types:
      - prereleased
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: curl -X POST -d {} https://api.vercel.com/v1/integrations/deploy/prj_PR9tg93nyYiGwX464db0c7SPMfs6/xSpVaALjVQ