name: "Deploy Beta"

on:
  release:
    types:
      - prereleased
jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "Deploy front-end"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn
      - uses: actions/vercel-deployment@0.5.1
        with:
          vercelToken: ${{ secrets.VERCEL_TOKEN }}
          vercelOrgId: ${{ secrets.VERCEL_ORG_ID }}
          vercelProjectId: ${{ secrets.VERCEL_PROJECT_ID }}
          assignDomain: "boardly.vercel.app"